### ISSUE TITLE
Template validation error

### ISSUE THREAD

**Issue by erikaulin** [nicolaka/ddc-aws#43]
During creation of stack I tried to change UCPNodesInstanceType size to m4.large but get error.

`: Template error: Unable to get mapping for AWSInstanceType2Arch::m4.large::Arch`

**Comment by nicolaka** [comment]
cc @bchav

**Comment by nicolaka** [comment]
@erikaulin looks like we're missing the Type2Arch mapping for that instance type. you can simply add the following under  "AWSInstanceType2Arch" to address it 

```
"m4.large": {
                "Arch": "HVM64"
```

we'll fix it in next release.

**Comment by erikaulin** [comment]
OK thanks learning more and more about AWS and cloudformation templates :)  I project forked and added all the m4 options.

**Comment by nicolaka** [comment]
fixed with #44
