### ISSUE TITLE
Custom UserData / Bootstrapping not supported

### ISSUE THREAD

**Issue by ahawkins** [nicolaka/ddc-aws#53]
We use DataDog to monitor some infrastructure. This requires an agent running on the host. I'd usually install that via UserData (or other way). Since the UCP nodes are in an ASG, UserData (or similar) support is required. I suggest an optional parameter for an external URL to fetch that is executed _after_ all the docker bits are run. I've made a similar PR to another project here https://github.com/buildkite/elastic-ci-stack-for-aws/pull/120.

**Comment by ahawkins** [comment]
@nicolaka should I submit a PR for this?

**Comment by nicolaka** [comment]
@ahawkins the goal of this CFN is to bootstrap DDC on AWS. Users who have other requirements such as monitoring agents..etc would need to either adjust the CFN or use their standard config management tools ( e.g Ansible, Puppet...etc) to deploy them. I dont feel that adding optional UserData is a good idea for this CFN.

**Comment by ahawkins** [comment]
@nicolaka I get that. Doing that forces users to now maintain their own CloudFormation template. I guess I'll have to do that. Seems my scope is larger than this project's.
